version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Logging in to Amazon ECR...
      - "AWS_REGION=us-east-1"
      - "AWS_ACCOUNT_ID=423623860069"
      - "IMAGE_REPO_NAME=crackerfrontend"
      - "aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
      - "COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)"
      - "IMAGE_TAG=${COMMIT_HASH:=latest}"
      - "REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME"

  build:
    commands:
      - "docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG ."
      - "docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG"

  post_build:
    commands:
      - "echo Repository URI: $REPOSITORY_URI"
      - "echo Image tag: $IMAGE_TAG"
      - "docker images"
      - "echo Pushing Docker image to ECR..."
      - "docker push $REPOSITORY_URI:$IMAGE_TAG"
