version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # Log in to Amazon ECR
      - echo "Logging in to Amazon ECR..."
     
  pre_build:
    commands:
      # Define AWS region, ECR repository, and Docker image tag
      - AWS_REGION=us-east-2  # Set the AWS region
      - REPOSITORY_URI=423623860069.dkr.ecr.us-east-2.amazonaws.com/ui
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - IMAGE_TAG=latest 
  build:
    commands:
      # Build the Docker image
      - echo "Building the Docker image..."
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      # Push the Docker image to ECR
      - echo "Pushing the Docker image to Amazon ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG

artifacts:
  files:
    - '**/*'
