name: Deploy React to Azure Blob Storage

on:
  push:
    branches: [ "main" ]  # Trigger on main branch push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # 2️⃣ Setup Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    # 3️⃣ Install project dependencies
    - name: Install dependencies
      run: npm install

    # 4️⃣ Build the React application
    - name: Build React app
      run: npm run build

    # 5️⃣ DEBUG (optional) — Check if GitHub secrets are available
    - name: Check Azure secrets
      run: |
        echo "AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}"
        echo "AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}"
        echo "AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}"
        # Do NOT echo client secret in public repos
        # echo "AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}"

    # 6️⃣ Login to Azure using Service Principal
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

    # 7️⃣ Upload the build folder to Azure Blob Storage ($web container)
    - name: Upload React build to Blob Storage
      run: |
        az storage blob upload-batch \
          --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} \
          --auth-mode login \
          -d '$web' \
          -s build
