name: Trigger auto deployment for frontendweb

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/frontendweb-AutoDeployTrigger-68521eb9-b9c6-4797-8f78-6a1a0f62ce70.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FRONTENDWEB_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FRONTENDWEB_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FRONTENDWEB_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.FRONTENDWEB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FRONTENDWEB_REGISTRY_PASSWORD }}
          containerAppName: frontendweb
          resourceGroup: demo
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


