name: Trigger auto deployment for groups

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/groups-AutoDeployTrigger-cc7c8382-220a-4e75-917e-5c3a13f42aa1.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.GROUPS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.GROUPS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.GROUPS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/root
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: fronty.azurecr.io
          registryUsername: ${{ secrets.GROUPS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GROUPS_REGISTRY_PASSWORD }}
          containerAppName: groups
          resourceGroup: demo
          imageToBuild: fronty.azurecr.io/groups:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


